name: Build .Net core test

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build .Net core lib
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
